### ASSOCIATION RULE

The Objective of this assignment is to introduce students to rule mining techniques, particularly focusing on market basket analysis and provide hands on experience.

##### Dataset:

Use the Online retail dataset to apply the association rules.

##### Data preprocession:

Pre-process the dataset to ensure it is suitable for Association rules, this may include handling missing values, removing duplicates, and converting the data to appropriate format.

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\akshata\anaconda3\lib\site-packages (0.23.1)
Requirement already satisfied: scipy>=1.2.1 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (3.8.4)
Requirement already satisfied: joblib>=0.13.2 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\akshata\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\akshata\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\akshata\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\akshata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [6]:

df = pd.read_csv(r"C:\Users\Akshata\OneDrive\Desktop\Assignment\Association Rules\Online retail.csv",header=None)
display(df.head())
print(df.shape)

                                                   0
0  shrimp,almonds,avocado,vegetables mix,green gr...
1                             burgers,meatballs,eggs
2                                            chutney
3                                     turkey,avocado
4  mineral water,milk,energy bar,whole wheat rice...

(7501, 1)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7501 entries, 0 to 7500
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7501 non-null   object
dtypes: object(1)
memory usage: 58.7+ KB

In [8]:
pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\akshata\anaconda3\lib\site-packages (0.23.1)
Requirement already satisfied: scipy>=1.2.1 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (3.8.4)
Requirement already satisfied: joblib>=0.13.2 in c:\users\akshata\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\akshata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\akshata\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\akshata\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\akshata\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\akshata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
df.columns

Index([0], dtype='int64')

In [10]:
df.describe()

              0
count      7501
unique     5176
top     cookies
freq        223

In [11]:
df.isnull().sum()

0    0
dtype: int64

In [12]:
df.fillna('', inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)
transactions = []
for i in range(len(df)):
    transactions.append(df.iloc[i, 0].split(','))

In [26]:
# Create a pandas dataframe from the transactions
df = pd.DataFrame(transactions).T

In [28]:
df

,0,1,2,3,4,5,6,7,8,9,...,5166,5167,5168,5169,5170,5171,5172,5173,5174,5175
0,shrimp,burgers,chutney,turkey,mineral water,low fat yogurt,whole wheat pasta,soup,frozen vegetables,french fries,...,chocolate,fresh tuna,parmesan cheese,red wine,herb & pepper,burgers,turkey,butter,burgers,eggs
1,almonds,meatballs,None,avocado,milk,None,french fries,light cream,spaghetti,None,...,shrimp,parmesan cheese,champagne,tomato sauce,spaghetti,salmon,burgers,light mayo,frozen vegetables,frozen smoothie
2,avocado,eggs,None,None,energy bar,None,None,shallot,green tea,None,...,pasta,whole wheat pasta,white wine,spaghetti,low fat yogurt,pancakes,dessert wine,fresh bread,eggs,yogurt cake
3,vegetables mix,None,None,None,whole wheat rice,None,None,None,None,None,...,spaghetti,french wine,None,chocolate,None,french fries,shrimp,None,french fries,low fat yogurt
4,green grapes,None,None,None,green tea,None,None,None,None,None,...,None,fromage blanc,None,olive oil,None,frozen smoothie,pasta,None,magazines,None
5,whole weat flour,None,None,None,None,None,None,None,None,None,...,None,cottage cheese,None,french fries,None,fresh bread,tomatoes,None,green tea,None
6,yams,None,None,None,None,None,None,None,None,None,...,None,brownies,None,salt,None,mint,pepper,None,None,None
7,cottage cheese,None,None,None,None,None,None,None,None,None,...,None,salad,None,asparagus,None,None,milk,None,None,None
8,energy drink,None,None,None,None,None,None,None,None,None,...,None,mint,None,None,None,None,pancakes,None,None,None
9,tomato juice,None,None,None,None,None,None,None,None,None,...,None,green tea,None,None,None,None,whole wheat rice,None,None,None
10,low fat yogurt,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,oil,None,None,None
11,green tea,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,frozen smoothie,None,None,None
12,honey,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
13,salad,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
14,mineral water,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
15,salmon,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
16,antioxydant juice,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
17,frozen smoothie,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
18,spinach,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
19,olive oil,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [30]:
df.shape

(20, 5176)

In [32]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,5166,5167,5168,5169,5170,5171,5172,5173,5174,5175
count,20,3,1,2,5,1,2,3,3,1,...,4,10,3,8,3,7,12,3,6,4
unique,20,3,1,2,5,1,2,3,3,1,...,4,10,3,8,3,7,12,3,6,4
top,shrimp,burgers,chutney,turkey,mineral water,low fat yogurt,whole wheat pasta,soup,frozen vegetables,french fries,...,chocolate,fresh tuna,parmesan cheese,red wine,herb & pepper,burgers,turkey,butter,burgers,eggs
freq,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Columns: 5176 entries, 0 to 5175
dtypes: object(5176)
memory usage: 808.9+ KB

In [36]:
df.isnull().sum()

0        0
1       17
2       19
3       18
4       15
        ..
5171    13
5172     8
5173    17
5174    14
5175    16
Length: 5176, dtype: int64

In [38]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5171,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5172,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,False
5173,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5174,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5175,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [40]:
from mlxtend.frequent_patterns import apriori, association_rules

# Calculate frequent itemsets using Apriori
frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)

# Generate association rules
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.5)

# Set appropriate threshold for support, confidence, and lift
rules = rules[(rules['support'] > 0.01) & (rules['confidence'] > 0.5) & (rules['lift'] > 1.5)]

# Print the generated rules
print(rules)

                        antecedents      consequents  antecedent support  \
0              (chicken, chocolate)  (mineral water)            0.021252
1            (olive oil, chocolate)  (mineral water)            0.023570
2               (ground beef, eggs)  (mineral water)            0.028787
3  (frozen vegetables, ground beef)  (mineral water)            0.024536
4  (frozen vegetables, ground beef)      (spaghetti)            0.024536
5               (milk, ground beef)  (mineral water)            0.031685
6           (ground beef, pancakes)  (mineral water)            0.020866
7                 (olive oil, milk)  (mineral water)            0.024150
8                      (milk, soup)  (mineral water)            0.021445
9                 (spaghetti, soup)  (mineral water)            0.020672

   consequent support   support  confidence      lift  leverage  conviction  \
0            0.299845  0.011012    0.518182  1.728163  0.004640    1.453151
1            0.299845  0.011978    0.508197  1.694862  0.004911    1.423648
2            0.299845  0.014490    0.503356  1.678717  0.005858    1.409771
3            0.299845  0.013331    0.543307  1.811957  0.005974    1.533097
4            0.229521  0.012558    0.511811  2.229911  0.006926    1.578240
5            0.299845  0.016036    0.506098  1.687861  0.006535    1.417597
6            0.299845  0.010819    0.518519  1.729286  0.004563    1.454167
7            0.299845  0.012365    0.512000  1.707546  0.005124    1.434743
8            0.299845  0.012365    0.576577  1.922913  0.005935    1.653557
9            0.299845  0.010819    0.523364  1.745448  0.004621    1.468952

   zhangs_metric
0       0.430500
1       0.419878
2       0.416291
3       0.459382
4       0.565425
5       0.420869
6       0.430714
7       0.424619
8       0.490474
9       0.436096

In [42]:
# Analyze the generated rules
interesting_rules = rules.nlargest(10, 'lift')

# Interpret the results and provide insights into customer purchasing behavior
print("Top 10 rules with highest lift:")
print(interesting_rules)

Top 10 rules with highest lift:
                        antecedents      consequents  antecedent support  \
4  (frozen vegetables, ground beef)      (spaghetti)            0.024536
8                      (milk, soup)  (mineral water)            0.021445
3  (frozen vegetables, ground beef)  (mineral water)            0.024536
9                 (spaghetti, soup)  (mineral water)            0.020672
6           (ground beef, pancakes)  (mineral water)            0.020866
0              (chicken, chocolate)  (mineral water)            0.021252
7                 (olive oil, milk)  (mineral water)            0.024150
1            (olive oil, chocolate)  (mineral water)            0.023570
5               (milk, ground beef)  (mineral water)            0.031685
2               (ground beef, eggs)  (mineral water)            0.028787

   consequent support   support  confidence      lift  leverage  conviction  \
4            0.229521  0.012558    0.511811  2.229911  0.006926    1.578240
8            0.299845  0.012365    0.576577  1.922913  0.005935    1.653557
3            0.299845  0.013331    0.543307  1.811957  0.005974    1.533097
9            0.299845  0.010819    0.523364  1.745448  0.004621    1.468952
6            0.299845  0.010819    0.518519  1.729286  0.004563    1.454167
0            0.299845  0.011012    0.518182  1.728163  0.004640    1.453151
7            0.299845  0.012365    0.512000  1.707546  0.005124    1.434743
1            0.299845  0.011978    0.508197  1.694862  0.004911    1.423648
5            0.299845  0.016036    0.506098  1.687861  0.006535    1.417597
2            0.299845  0.014490    0.503356  1.678717  0.005858    1.409771

   zhangs_metric
4       0.565425
8       0.490474
3       0.459382
9       0.436096
6       0.430714
0       0.430500
7       0.424619
1       0.419878
5       0.420869
2       0.416291

Interview Questions:
1. 	What is lift and why is it important in Association rules
* Lift is a measure of the strength of the association between two items, taking into account the frequency of both items in the dataset.
* It is calculated as the confidence of the association divided by the support of the second item.
* lift, can be used to compare observed confidence with expected confidence, or how many times an if-then statement is expected to be found true.

ue.

ng?

2.	What is support and Confidence. How do you calculate them?

Support is calculated by dividing the number of transactions containing an item set by the total number of transactions.
Support indicates how frequently an item appears in the data

.

Confidence is calculated by dividing the number of transactions containing both itemsets by the number of transactions containing the first itemset.
Confidence indicates the number of times the if-then statement is found to be true.

3.	What are some limitations or challenges of Association rules mining?

Some of the main drawbacks of association rule algorithms in e-learning are: the algorithms have too many parameters for some in experienced person in data mining 
and the obtained rules are in abundance, most of them non-interesting and with low unambiguousness.
potential to generate an overwhelming number of rules from a large dataset, which can be costly and complex to analyze. 
To address this issue, you can use techniques to reduce the search space and filter out irrelevant or redundant rules.